### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by Sliman4** [Sliman4/bevy_slinet#6]
Hey everyone, it's been more than a year since I abandoned this project, and I won't be actively working on it anytime soon, so I think it'd be better if someone active maintained bevy_slinet.

Pinging contributors if anyone's interested: @arilotter @aggyomfg @de-grote

**Comment by aggyomfg** [comment]
Hi! I will take it, but not as a priority, only if others don't want it

**Comment by Sliman4** [comment]
Great, let's wait for 1-2 weeks to see if someone else's interested.

**Comment by de-grote** [comment]
Thanks for the offer, I don't really have any expierence maintaining librairies on crates.io or networking in general, so I won't be taking this job. Altough I'm fine with doing some PRs for simpler updates when needed.

**Comment by ethernet8023** [comment]
Thanks for the tag! I don't have any bandwidth to maintain this crate, but wish you all luck :)

**Comment by aggyomfg** [comment]
@Sliman4 looks like I'll take it :)

**Comment by Sliman4** [comment]
@aggyomfg Sorry for not responding for so long lol, completely forgot about this github account. If you're interested in this, send me your crates.io username (either here or in telegram `@sliman4444`) and I'll add you as an owner there and in this repo

**Comment by aggyomfg** [comment]
Repo ownership and crates.io ownership trasfered to me.
